# Generated by Django 4.2.4 on 2023-09-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
