# Generated by Django 4.2.4 on 2023-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_is_fragile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='/placeholder.png', null=True, upload_to='uploads/brands/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/placeholder.png', null=True, upload_to='uploads/categories/'),
        ),
    ]
